SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800
SCREEN_TITLE = "Galaga"

# Background Constants
BACKGROUND_SPRITE_SPEED = 100
BACKGROUND_SPRITE_FREQ = 120
BACKGROUND_SPRITE_SIZE = 2

# User Constants
SPRITE_SCALE_USER = 0.04
SPRITE_SCALE_LIVES = 0.02
USER_SPEED = 2.0

# User Explosion Animation Constants, must be ints
LOWER_FRAME_BOUND = 1
UPPER_FRAME_BOUND = 5
FRAME_SPEED = 4

#Movement Constants
UNIT_VECTOR_UP = [0.0,1.0]
UNIT_VECTOR_DOWN = [0.0,-1.0]


# Enemy Constants
SPRITE_SCALING_BUG = 2.10
SPRITE_SCALING_BUTTERFLY = 2.5
ENEMY_SPEED = 1.25
ENEMY_INITIAL_SPACING = 25
ENEMY_UPDATE_INTERVAL = 25
# Pellet Constants
PELLET_SPEED = 8
SPRITE_SCALE_PELLET = .10